name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install launcheon package
      uses: ./.github/actions/launcheon_build  
    - name: Linting
      run: |
        uv run --frozen --group dev -m ruff check launcheon
        uv run --frozen --group dev -m ruff format --check launcheon
